### ISSUE TITLE
Deploying @lighthouse-web3/sdk to vercel serve doesn't work, but it works fine locally

### ISSUE THREAD

**Issue by noyobo** [lighthouse-web3/lighthouse-package#114]
<img width="853" alt="image" src="https://github.com/user-attachments/assets/00b67fb9-90b1-4ce2-9a41-a002cd3dc4e9">

**Comment by nandit123** [comment]
Hi, there is a new version of package going live likely this week that may resolve this issue.

**Comment by noyobo** [comment]
Thanks. According to the source code, I have changed to post by myself using `api/v0/add`, it working on vercel serve


```js
const formData = new FormData();
  formData.append('file', buffer, { contentType: type });
  const res = await fetch('https://node.lighthouse.storage/api/v0/add', {
    method: 'POST',
    body: formData,
    headers: {
      Encryption: 'false',
      Authorization: `Bearer ${token}`,
    },
  });
```

Next time I use the SDK, I will give you feedback based on the situation.

**Comment by toufique-imam** [comment]
Still facing this issue in 0.3.4
