### ISSUE TITLE
Broken shebangs in NPM package

### ISSUE THREAD

**Issue by rhdeck** [lighthouse-web3/lighthouse-package#61]
On the current NPM (0.1.2) the text files are all terminated \r\n rather than \n. This is breaking the shebang and the code won't run, at least in my MacOS environment running node LTS (16.16). The code appears fine (source code seems to be in LF rather than CRLF mode) so this is probably a side-effect of the last publish to npm. Another publish, potentially from a non-windows machine or after confirming the line ending sequence should fix you right up!

**Comment by nandit123** [comment]
Thanks @rhdeck for raising this issue. Will fix this in our next package update.

**Comment by ravish1729** [comment]
HI @rhdeck, the issue has been resolved in PR #68 . We have shifted from LF to CRLF mode. Thanks for pointing out the issue.
