### ISSUE TITLE
Decrpty and shareFile 

### ISSUE THREAD

**Issue by kaushikc44** [lighthouse-web3/lighthouse-package#80]
![image](https://user-images.githubusercontent.com/59849731/205459281-b8d07b8c-fca1-41a6-bd12-172c9f165949.png)
Hi , shouldn't the on click be shareFile rather than decrypt?

**Comment by ravish1729** [comment]
Resolved: issue related to Gitbook- https://github.com/lighthouse-web3/gitbook
