### ISSUE TITLE
Getting alot of errors , while trying to share files 

### ISSUE THREAD

**Issue by kaushikc44** [lighthouse-web3/lighthouse-package#81]

**Comment by kaushikc44** [comment]
Sorry  it got posted by mistake , anyways I am getting a lot of
![image](https://user-images.githubusercontent.com/59849731/205459397-8b0c4c1a-f465-42a1-bb69-b755eb38a985.png)
 API errors , cant really understand why ?
The same errors are repeated multiple times. Please do let me know a way around , Trying to implement this feature.

**Comment by ravish1729** [comment]
The docs are updated for share refer to Gitbook.
